express-notes-api | Samuel Cho
Samuel-Cho/c0121-code-solutions pull request #91
Opened 2021-03-17 04:20 UTC by Samuel-Cho

Built a small API to create, read, update, and delete notes.
<img width="1909" alt="Screen Shot 2021-03-16 at 5 30 22 PM" src="https://user-images.githubusercontent.com/76749207/111414213-d0246b80-869c-11eb-97e9-f3d7391334a9.png">
<img width="1102" alt="Screen Shot 2021-03-16 at 7 29 34 PM" src="https://user-images.githubusercontent.com/76749207/111414224-d61a4c80-869c-11eb-9786-99aac85d8225.png">
<img width="1099" alt="Screen Shot 2021-03-16 at 7 30 14 PM" src="https://user-images.githubusercontent.com/76749207/111414227-d74b7980-869c-11eb-99a8-d394b7d5f9b0.png">
<img width="1104" alt="Screen Shot 2021-03-16 at 7 30 43 PM" src="https://user-images.githubusercontent.com/76749207/111414229-d87ca680-869c-11eb-82d1-a51d99666e78.png">
<img width="1105" alt="Screen Shot 2021-03-16 at 7 30 56 PM" src="https://user-images.githubusercontent.com/76749207/111414231-d9153d00-869c-11eb-9d8f-52b058a5210e.png">
<img width="1092" alt="Screen Shot 2021-03-16 at 8 02 45 PM" src="https://user-images.githubusercontent.com/76749207/111414234-da466a00-869c-11eb-9693-4db9a256df98.png">
<img width="1105" alt="Screen Shot 2021-03-16 at 8 03 00 PM" src="https://user-images.githubusercontent.com/76749207/111414238-db779700-869c-11eb-9660-3c53231226be.png">
<img width="1100" alt="Screen Shot 2021-03-16 at 8 03 13 PM" src="https://user-images.githubusercontent.com/76749207/111414240-dca8c400-869c-11eb-8cb2-0853c24fd5a0.png">
<img width="1892" alt="Screen Shot 2021-03-16 at 8 10 28 PM" src="https://user-images.githubusercontent.com/76749207/111414243-ddd9f100-869c-11eb-9b42-0cd2adb912d6.png">
<img width="1105" alt="Screen Shot 2021-03-16 at 8 25 36 PM" src="https://user-images.githubusercontent.com/76749207/111414249-dfa3b480-869c-11eb-94cf-1ba5eb01487e.png">
<img width="1106" alt="Screen Shot 2021-03-16 at 8 26 13 PM" src="https://user-images.githubusercontent.com/76749207/111414251-e0d4e180-869c-11eb-9c28-e312274b6d70.png">
<img width="1110" alt="Screen Shot 2021-03-16 at 8 32 17 PM" src="https://user-images.githubusercontent.com/76749207/111414254-e16d7800-869c-11eb-89db-c39f14e1012c.png">
<img width="1119" alt="Screen Shot 2021-03-16 at 8 34 12 PM" src="https://user-images.githubusercontent.com/76749207/111414257-e2060e80-869c-11eb-8745-fa4ffb02ca6e.png">
<img width="1103" alt="Screen Shot 2021-03-16 at 9 04 20 PM" src="https://user-images.githubusercontent.com/76749207/111414260-e3373b80-869c-11eb-9d7d-03e784d4f75b.png">
<img width="1108" alt="Screen Shot 2021-03-16 at 9 04 59 PM" src="https://user-images.githubusercontent.com/76749207/111414262-e4686880-869c-11eb-905a-9ac7a40d0128.png">
<img width="1107" alt="Screen Shot 2021-03-16 at 9 05 48 PM" src="https://user-images.githubusercontent.com/76749207/111414265-e5999580-869c-11eb-8baa-ebabe301cf81.png">
<img width="1108" alt="Screen Shot 2021-03-16 at 9 07 14 PM" src="https://user-images.githubusercontent.com/76749207/111414267-e6cac280-869c-11eb-8823-1dba5f800d73.png">
<img width="1889" alt="Screen Shot 2021-03-16 at 9 08 07 PM" src="https://user-images.githubusercontent.com/76749207/111414271-e7635900-869c-11eb-906e-3626e7c67975.png">

2021-03-17 22:22 UTC, thebearingedge requested changes

2021-03-17 22:22 UTC, thebearingedge commented on express-notes-api/deleteNote.js
> +        res.status(204).end();
Be sure that it is impossible for the server to try to respond more than once to the same request. You'll need an `else` in here.

2021-03-17 22:22 UTC, thebearingedge commented on express-notes-api/postNote.js
> +      res.status(201).json(req.body);
Be sure that it is impossible for the server to try to respond more than once to the same request. You'll need an `else` in here.

2021-03-17 22:22 UTC, thebearingedge commented on express-notes-api/putNote.js
> +      res.status(200).json(data.notes[req.params.id]);
Be sure that it is impossible for the server to try to respond more than once to the same request. You'll need an `else` in here.

2021-03-17 22:29 UTC, Samuel-Cho commented
<img width="835" alt="Screen Shot 2021-03-17 at 3 25 40 PM" src="https://user-images.githubusercontent.com/76749207/111546836-82a80d00-8735-11eb-9bbd-2acbd064cb04.png">
<img width="802" alt="Screen Shot 2021-03-17 at 3 26 17 PM" src="https://user-images.githubusercontent.com/76749207/111546840-8471d080-8735-11eb-863f-d4cab0011dcb.png">
<img width="799" alt="Screen Shot 2021-03-17 at 3 26 53 PM" src="https://user-images.githubusercontent.com/76749207/111546843-85a2fd80-8735-11eb-9764-2cf8d0e942fc.png">

2021-03-18 17:21 UTC, thebearingedge approved these changes

2021-03-18 18:45 UTC, merged